/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (c) 2026 NotBlackMagic (PlumaLabs)
 *
 * File:    Instinct/Modules/Vision/imageWriter.hpp
 * Author:  NotBlackMagic
 * Brief:   Stateless utility class for formatting and saving static images to storage.
 */

#pragma once

#include <stdint.h>

#include "logger.hpp"
#include "status.hpp"
#include "visionTypes.hpp"

#include "fx_api.h"

class ImageWriter {
	public:
		// Delete constructor.
		ImageWriter() = delete;

		/// @brief Saves raw uncompressed pixel data (e.g., RGB565) as a standard BMP file.
		/// @param frame	The raw image buffer and metadata.
		/// @param media	Reference to the initialized FileX media.
		/// @param fileName	The target file name (e.g., "snap0001.bmp").
		/// @return Status::Ok on success, Status::Error on file system failure.
		static Status SaveBMP(const VisionFrame& frame, FX_MEDIA& media, const char* fileName);

		static Status SaveBinary(const VisionFrame& frame, FX_MEDIA& media, const char* fileName);

		/// @brief Saves a pre-compressed JPEG bitstream directly to a file.
		/// @param packet	The compressed media packet (generated by the hardware encoder).
		/// @param media	Reference to the initialized FileX media.
		/// @param fileName	The target file name (e.g., "snap0001.jpg").
		/// @return Status::Ok on success, Status::Error on file system failure.
		// static Status SaveJpeg(const MediaPacket& packet, FX_MEDIA& media, const char* fileName);

		/// @brief Opens a file stream for streaming/recording (e.g., H.264 video).
		/// @param file			Reference to opened file.
		/// @param media		Reference to the initialized FileX media.
		/// @param fileName		The target file name (e.g., "snap0001.bmp").
		/// @param headerFrame	The H264 image header buffer.
		/// @param allocSize	Size to pre-allocate in the file system, in bytes.
		/// @return Status::Ok on success, Status::Error on file system failure.
		static Status OpenStream(FX_FILE& file, FX_MEDIA& media, const char* fileName, const VisionFrame& headerFrame, uint32_t allocSize);

		/// @brief Appends a frame to an active stream file.
		/// @param file		Reference to opened file.
		/// @param frame	The H264 image buffer.
		/// @return Status::Ok on success, Status::Error on file system failure.
		static Status AppendStream(FX_FILE& file, const VisionFrame& frame);

		/// @brief Closes and flushes an active stream file.
		/// @param file		Reference to opened file.
		/// @param media	Reference to the initialized FileX media.
		/// @return Status::Ok on success, Status::Error on file system failure.
		static Status CloseStream(FX_FILE& file, FX_MEDIA& media);
};