/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (c) 2026 NotBlackMagic (PlumaLabs)
 *
 * File:	Instinct/Modules/Estimation/estimatorThread.hpp
 * Author:	NotBlackMagic
 * Brief:	Core navigation filter. Subscribes to Virtual Sensors, executes the InEKF on the SE_2(3) manifold, and publishes the vehicle State.
 */

#pragma once

#include "hardware.hpp"

#include "logger.hpp"
#include "pubSub.hpp"
#include "rotations.hpp"

#include "inEKF.hpp"

#include "tx_api.h"

class EstimatorThread {
	public:
		// Helper structure for Euler angles
		struct EulerAngles {
			float roll;
			float pitch;
			float yaw;
		};

		static void Init();

	private:
		static TX_THREAD threadPtr;
		static uint8_t threadStack[16384]; // EKF math needs a generous stack!

		// Topic Instance IDs
		// Virtual sensor generated by the sensor hub are instance 255
		static constexpr uint8_t virtualInstanceID = 255;

		// Sensor Subscribers
		static Subscriber<IMUMsg> subVirtualIMU;
        static Subscriber<MagMsg> subVirtualMag;
        static Subscriber<BaroMsg> subVirtualBaro;

		// Subscriber Topic Pointers
		static Topic<IMUMsg>* topicVirtualIMU;
		static Topic<MagMsg>* topicVirtualMag;
		static Topic<BaroMsg>* topicVirtualBaro;

		// Output state publisher
		static Topic<StateMsg> topicState;

		// The Core Math Engine
		static InEKF filter;

		static void Run(ULONG input);
};